In [1]:
import pandas as pd

In [7]:
hap = pd.read_csv('dataframes/cleanData.csv')

In [8]:
hap.head()

,country,year,sex,age,suicides_no,population,suicides/100kpop,country-year,gdp_for_year,gdp_per_capita,generation,popNorma
0,Albania,1987,1,2,21,312900,6.71,Albania1987,"2,156,624,900",796,4,0.007137
1,Albania,1987,1,4,16,308000,5.19,Albania1987,"2,156,624,900",796,2,0.007025
2,Albania,1987,2,2,14,289700,4.83,Albania1987,"2,156,624,900",796,4,0.006607
3,Albania,1987,1,6,1,21800,4.59,Albania1987,"2,156,624,900",796,1,0.000491
4,Albania,1987,1,3,9,274300,3.28,Albania1987,"2,156,624,900",796,3,0.006256